.PHONY : ALL
ALL : t3.2 t3.3 t3.3_1 t3.4

t3.2 : t3.2.c
	gcc -std=c99 -Wall -o t3.2 t3.2.c

t3.3 : t3.3.c
	gcc -std=c99 -Wall -o t3.3 t3.3.c

t3.3_1 : t3.3_1.c
	gcc -std=c99 -Wall -o t3.3_1 t3.3_1.c

t3.4 : t3.4.c
	gcc -std=c99 -Wall -o t3.4 t3.4.c

.PHONY : clean 
clean :
	rm -rf t3.2 t3.3 t3.3_1 t3.4
