.PHONY : ALL
ALL : t3.2 t3.3 t3.3_1 t3.4 t3.5 t3.6 e1 e2 e3 e4 e5 e6 e7

t3.2 : t3.2.c
	gcc -std=c99 -Wall -o t3.2 t3.2.c

t3.3 : t3.3.c
	gcc -std=c99 -Wall -o t3.3 t3.3.c

t3.3_1 : t3.3_1.c
	gcc -std=c99 -Wall -o t3.3_1 t3.3_1.c

t3.4 : t3.4.c
	gcc -std=c99 -Wall -o t3.4 t3.4.c

t3.5 : t3.5.c
	gcc -std=c99 -Wall -o t3.5 t3.5.c

t3.6 : t3.6.c
	gcc -std=c99 -Wall -o t3.6 t3.6.c

e1 : e1.c
	gcc -std=c99 -Wall -o e1 e1.c

e2 : e2.c
	gcc -std=c99 -Wall -o e2 e2.c

e3 : e3.c
	gcc -std=c99 -Wall -o e3 e3.c

e4 : e4.c
	gcc -std=c99 -Wall -o e4 e4.c

e5 : e5.c
	gcc -std=c99 -Wall -o e5 e5.c

e6 : e6.c
	gcc -std=c99 -Wall -o e6 e6.c

e7 : e7.c
	gcc -std=c99 -Wall -o e7 e7.c
.PHONY : clean 
clean :
	rm -rf t3.2 t3.3 t3.3_1 t3.4 t3.5 t3.6 e1 e2 e3 e4 e5 e6 e7
